# Generated by Django 2.2.14 on 2020-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180522_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.CharField(max_length=300, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='send_email',
            field=models.BooleanField(default=False, help_text='If checked, the person entering the form will be sent an email', verbose_name='Send email'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(editable=False, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Title'),
        ),
    ]
